//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class change
    {
        public int changeID { get; set; }
        public int userID { get; set; }
        public int projectID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string changeSummary { get; set; }
    
        public virtual user user { get; set; }
        public virtual project project { get; set; }
    }
}
