//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.changes = new HashSet<change>();
        }
    
        public int projectID { get; set; }
        public int userID { get; set; }
        public string pName { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string projectStage { get; set; }
        public string projectFile { get; set; }
        public string pDesc { get; set; }
        public string pAbstract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<change> changes { get; set; }
        public virtual user user { get; set; }
    }
}
