//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;

    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.changes = new HashSet<change>();
        }
        [Display(Name ="Project ID")]
        public int projectID { get; set; }
        [Display(Name = "User ID")]
        public int userID { get; set; }
        [Display(Name = "Project Name")]
        public string pName { get; set; }
        [Display(Name = "Project Creation Date")]
        public System.DateTime dateCreated { get; set; }
        [Display(Name = "Project Stage")]
        public string projectStage { get; set; }
        [Display(Name = "Project File")]
        public string projectFile { get; set; }
        [Display(Name = "Project Description")]
        public string pDesc { get; set; }
        [Display(Name = "Project Abstract")]
        public string pAbstract { get; set; }

        public string pPFileDisplay {
            get
            {
                return (this.pName + "-ExpenditureFile" + Path.GetExtension(this.projectFile));
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<change> changes { get; set; }
        public virtual user user { get; set; }
    }
}
