//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.changes = new HashSet<change>();
            this.projects = new HashSet<project>();
        }

        [Display(Name = "User ID")]
        public int userID { get; set; }
        [Display(Name = "User Forename")]
        public string forename { get; set; }
        [Display(Name = "User Surname")]
        public string surname { get; set; }
        [Display(Name = "User Role")]
        public string staffPosition { get; set; }
        public string hash { get; set; }
        public string salt { get; set; }
        [Display(Name = "User Email")]
        public string Email { get; set; }
        [Display(Name = "User Matriculation")]
        public string Matric { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<change> changes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
    }
}
